$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$ImageDir = Get-ChildItem -LiteralPath $Root -Directory |
    Where-Object { $_.Name -like '*images' } |
    ForEach-Object {
        Get-ChildItem -LiteralPath $_.FullName -Directory -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like '3*' } |
            Select-Object -First 1
    } |
    Where-Object { $null -ne $_ } |
    Select-Object -First 1

if ($null -eq $ImageDir) {
    throw "Slide 3 image directory was not found."
}

$Output = Join-Path $ImageDir.FullName 'slide3-images.js'
$ImageExtensions = @('.png', '.jpg', '.jpeg', '.webp', '.gif')
$RelativeImageDir = $ImageDir.FullName.Substring($Root.Length + 1).Replace('\', '/')

$Images = Get-ChildItem -LiteralPath $ImageDir.FullName -File |
    Where-Object { $ImageExtensions -contains $_.Extension.ToLowerInvariant() } |
    Sort-Object Name |
    ForEach-Object {
        "$RelativeImageDir/$($_.Name)"
    }

if ($Images.Count -eq 0) {
    throw "No slide 3 images found."
}

$Json = $Images | ConvertTo-Json
$Content = @"
// Auto-generated by refresh-slide3-images.ps1.
window.SLIDE3_BACKGROUND_IMAGES = $Json;
"@

Set-Content -LiteralPath $Output -Value $Content -Encoding UTF8
Write-Host "Slide 3 image manifest updated: $($Images.Count) images"
